name: '🚀 Continuous Delivery (CD)'

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - staging
    paths-ignore:
    - '.*'
    - '!.dockerignore'
    - 'CHANGELOG.md'
    - 'README.md'
    - 'docs/'
    - 'Makefile'
    - '.github/'
    - 'infrastructure.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  config:
    uses: ./.github/workflows/_config.yaml

  debug-outputs:
    needs: config
    runs-on: ubuntu-latest
    steps:
    - id: debug-context
      run: |
        echo "### Triggering Event"                                 >> $GITHUB_STEP_SUMMARY
        echo "| Var | Value |"                                      >> $GITHUB_STEP_SUMMARY
        echo "|:--|:--|"                                            >> $GITHUB_STEP_SUMMARY
        echo "| event_name      | ${{ github.event_name }} |"       >> $GITHUB_STEP_SUMMARY
        echo "| ref_name        | ${{ github.ref_name }} |"         >> $GITHUB_STEP_SUMMARY
        echo "| event.ref       | ${{ github.event.ref }} |"        >> $GITHUB_STEP_SUMMARY
        echo "| event.ref_type  | ${{ github.event.ref_type }} |"   >> $GITHUB_STEP_SUMMARY

        echo "### Pipeline Variables"                                         >> $GITHUB_STEP_SUMMARY
        echo "| Var | Value |"                                                >> $GITHUB_STEP_SUMMARY
        echo "|:--|:--|"                                                      >> $GITHUB_STEP_SUMMARY
        echo "| GitHub Environment | ${{ needs.config.outputs.github-env }}"  >> $GITHUB_STEP_SUMMARY
        echo "| AKS cluster | ${{ needs.config.outputs.cluster }}"            >> $GITHUB_STEP_SUMMARY
        echo "| Git sha | ${{ needs.config.outputs.git-sha }}"                >> $GITHUB_STEP_SUMMARY
        echo "| Docker Tag | ${{ needs.config.outputs.docker-tag }}"          >> $GITHUB_STEP_SUMMARY

  docker:
    needs: config
    uses: ./.github/workflows/_docker.yaml
    with:
      environment:  ${{ needs.config.outputs.github-env }}
      image-tag:    ${{ needs.config.outputs.docker-tag }}
      git-sha:      ${{ needs.config.outputs.git-sha }}
    secrets:
      AZURE_CLIENT_ID:                  ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID:            ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID:                  ${{ secrets.AZURE_TENANT_ID }}
      AZ_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
      AZ_DEFENDER_TOKEN:                ${{ secrets.AZ_DEFENDER_TOKEN }}
      SNYK_API_TOKEN:                   ${{ secrets.SNYK_API_TOKEN }}

  deploy:
    needs: config
    uses: ./.github/workflows/_deploy.yaml
    with:
      environment:         ${{ needs.config.outputs.github-env }}
      git-sha:             ${{ needs.config.outputs.git-sha }}
      image-tag:           ${{ needs.config.outputs.docker-tag }}
      resource-group:      ${{ needs.config.outputs.resource-group }}
      cluster-name:        ${{ needs.config.outputs.cluster }}
      cluster-namespace:   ${{ needs.config.outputs.cluster-namespace }}
      hostname:            ${{ needs.config.outputs.hostname }}
      overlays:            ./manifests/overlays/${{ needs.config.outputs.overlays }}
    secrets:
      AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}

  e2e:
    needs: [config, docker, deploy]
    uses: ./.github/workflows/_e2e.yaml
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    with:
      url:       ${{ needs.config.outputs.url }}
      build-sha: ${{ needs.config.outputs.git-sha }}
